version: '3.9'

services:
  app:
    container_name: project_app
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - project-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "4123:3306"
    env_file:
      - ./app/.env
    volumes:
      - .docker/db/sql:/sql
      - .docker/db/var:/var/lib/mysql
    networks:
      - project-network

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/html:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8765:80'
    networks:
      - project-network
    depends_on:
      - app

networks:
  project-network:
